### PR TITLE
grails 3 support

### PR DESCRIPTION
**Pull request by dtanner**
This is a rough cut of supporting grails 3 with the plugin.  Some notes to consider:
## Higher level stuff ##
- Grails 3 doesn't support `grails.config.locations` out of the box any more.  It automatically *does* include system and environment variables, but otherwise it looks like it wants you to put everything in application.yml, or an alternative groovy file.  Beyond that you're on your own, where you can put a hook into the Application startup.  Notes here: http://grails.1312388.n4.nabble.com/Grails-3-External-config-td4658823.html
Maybe one day I'll convert our apps to use etcd for everything, but until then, I think this plugin will still add value for a lot of people.  Along with continuing to support the concept of multiple config locations, the runtime reloading capability isn't provided by the framework.  

## Lower level stuff ##
The readme needs to be updated still, but here's how to try it out with a sample grails 3 app:  
1. do a local build of the plugin: `./gradlew install`
2. include the plugin in build.gradle: `runtime "org.grails.plugins:external-config-reload:1.5-SNAPSHOT"`
3. Add this to the application.yml:
```yml
grails:
    config:
        locations:
            - '/tmp/fooconfig.yml'
```

- I added yml support thanks to a tip from Burt Beckwith...turned out to be pretty easy.
- I tried to DRY up the checkNow and reloadNow methods, since they were mostly the same.  That did break 4 tests, complaining about notifyPluginsCalled being false...but I'm not sure it should actually notify plugins in all those situations.  I don't totally understand the automerge concept though, so I could use some input on that.
- log.trace doesn't work unless you use the @Slf4j annotation.  I don't usually use trace, but something to think about.  That might be a grails 3 quirk, or I might just not ever configure that properly.

Let me know what you think, and I can do some cleanup when it's looking good.

### CODE REVIEW

**Comment by bluesliverx** [comment]
Looks good to me.  Now I just need to figure out how to publish a plugin in grails 3, which I won't have time for a few days at least.
I'll go ahead and merge this in though.  I'll probably bump the version to 2.0 whenever I figure out deployment, and I'll probably use travisCI.

**Comment by dtanner** [comment]
ok thanks Brian.  There are a few failing tests...when you get the environment going to run them, let me know if you'd like me to make more changes.  Also FYI - with Grails 3 using Gradle, the codenarc and cobertura grails plugins have been replaced by their corresponding gradle plugins.  I didn't configure the gradle plugins yet though, so those reporting features aren't active yet.

**Comment by bluesliverx** [comment]
eh, it's ok.  I'm not big on code coverage for a little plugin like this, it was just a standard package I had for my grails plugins.

**Comment by bluesliverx** [comment]
For my future reference: https://github.com/grails-plugins/grails-webflow-plugin/blob/master/.travis.yml

**Comment by dtanner** [comment]
another example is in https://github.com/dtanner/grails-jasypt  
The build.gradle has an example config for binTray uploading.  The .travis.yml in there has `sudo: false`, which allows the build to run on Travis' newer docker container infrastructure.

**Comment by bluesliverx** [comment]
Almost there, fixing tests now...

**Comment by bluesliverx** [comment]
https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aexternal-config-reload/view

**Pull request merged**
